# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:namespace: messsage_sidekiq
:concurrency:  5
:queues:
  - [often, 7]
  - [default, 5]
  - [seldom, 3]
